language: c
compiler:
  - clang
  - gcc

dist: bionic

addons:
  apt:
    packages:
      - libcunit1
      - libcunit1-dev
      - libxml2

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake --build .
