language: c
compiler:
  - clang
  - gcc

dist: bionic

addons:
  apt:
    packages:
      - libxml2

script:
  - cmake --version
  - mkdir build && cd build && cmake -DBUILD_TESTING=ON -DENABLE_FUZZER=ON ..
  - make -j
