.\"	$Id$
.\"
.\" Copyright (c) 2018-2020 Sergey Bronnikov
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 29 2020 $
.Dt TESTRES.CGI 1
.Os
.Sh NAME
.Nm testres.cgi
.Nd hyperfast web viewer for software testing results
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility knits together software testing reports and helps analyze them.
.Nm
is able to process software testing reports in a three formats: JUnit, SubUnit
(versions 1 and 2) and Test Anything Protocol.
It is intended to be used in a
.Xr chroot 2
environment in
.Pa /var/www .
.Sh FILES
.Bl -tag -width "/var/www/conf/testres.css" -compact
.It Pa /var/www/conf/testres.css
CSS style sheet.
.El
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
.Rs
.%A M. G. Schwern, A. Lester, A. Armstrong
.%D 2003-2007
.%T TAP 13 - The Test Anything Protocol v13
.Re
.Pp
.Rs
.%A R. Collins
.%D 2009
.%T SubUnit: A streaming protocol for test results
.Re
.Pp
.Rs
.%A D. Robinson, K. Coar
.%D October 2004
.%R RFC 3875
.%T The Common Gateway Interface (CGI) Version 1.1
.Re
.Sh SEE ALSO
.Xr testres 1 ,
.Xr httpd 8 ,
.Xr slowcgi 8
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Sergey Bronnikov
