.\"	$Id$
.\"
.\" Copyright (c) 2018-2019 Sergey Bronnikov
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: January 26 2019 $
.Dt TESTRES 1
.Os
.Sh NAME
.Nm testres
.Nd A hyperfast web frontend for software testing results written in C.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl s Ar file
.Op Fl s Ar directory
.Op Fl t Ar name
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility knits together software testing reports.
It helps to store and analyze them.
.Nm
is able to process software testing reports in a three formats: JUnit, SubUnit
(versions 1 and 2) and Test Anything Protocol.
.Pp
The options are as follows:
.Bl -tag
.It Fl s
Set a source of reports.
Can be a regular file or multiple files in a directory.
.It Fl t
Set a testcase name and output metrics for a specified testcase name.
.It Fl v
Print version.
.El
.Pp
It supports two modes: console and web application.
.Sh USAGE
.Bl -tag -width Ds
.It Pa Console application
by default prints summary when specified directory with multiple reports and
detailed information in case of file with a single report.
When testcase name is specified
.Nm
calculates and prints useful metrics: average time of test execution and APFD
(Average Percentage of Faults Detected).
APFD measures the weighted average of the percentage of faults detected over
the life of a test suite.
APFD values ranges from 0 to 100, higher number simply faster fault detection rates.
A higher APFD value indicates faster (or  better) fault detection rate.
.It Pa Web application
works as a CGI application.
Allows to show a list with latest reports and detailed information of a separate report.
.El
.Sh FORMATS
.Nm
supports three the most popular software testing report formats: TAP
(TestAnythingProtocol), SubUnit (version 1 and 2) and JUnit.
.Bl -tag -width Ds
.It Pa JUnit "   "
The JUnit XML Report output comes from a build tool called Nant, as opposed to
the JUnit project itself - thus it can be a little tricky to nail down an
official spec for the format, even though it's widely adopted and used.
There have been a number of attempts to codify the schema, first off there is
an XSD for JUnit. Files with JUnit reports must have .xml extension.
.It Pa Test Anything Protocol
is a simple text-based interface between testing modules a test harness.
Files with TAP reports must have .tap extension.
.It Pa SubUnit
is a streaming protocol for test results.
It allows communication between unit tests and a test harness.
Originally developed for unit testing in 2005 by Robert Collins.
There are two major revisions of the protocol.
Version 1 was trivially human readable but had significant defects.
Version 1.1 added encapsulation of binary streams which mitigated some of the
issues but the core remained.
Version 2 shares many of the good characteristics of Version 1 and it still
models xUnit style test execution.
Files with SubUnit reports must have .subunit extension.
.El
.Sh FILES
.Bl -tag -width "/var/www/conf/testres.css" -compact
.It Pa /var/www/conf/testres.css
CSS style sheet.
.It Pa /var/www/conf/favicon.ico
favicon.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Bd -literal

$ testres -s reports/
-------------------------------------------------------------
DATE            PASS  FAIL  SKIP FILE
-------------------------------------------------------------
10/30/18 23:40     3     4     0 /home/sergeyb/testres/db/junit-min.xml
10/30/18 23:40  1760   689     0 /home/sergeyb/testres/db/junit.xml
10/30/18 23:40     1     0     1 /home/sergeyb/testres/db/subunit_v1-min.subunit
10/30/18 23:40 20358    57  2533 /home/sergeyb/testres/db/subunit_v1.subunit
10/30/18 23:40     1     2     1 /home/sergeyb/testres/db/testanything-min.tap
10/30/18 23:40     6     0     0 /home/sergeyb/testres/db/testanything.tap

$ testres -s web/subunit_v1.subunit

TEST REPORT (SUBUNIT_V1)
ID: b09b24ebda9e4725552bf89f9afdd9d04ab1cab
CREATED ON: Thu Jan  1 03:00:00 1970
FILE: web/subunit_v1.subunit

SUITE: noname
        PASS test_add.TestAdd.test_add_control_dir(pre-views)
        PASS test_add.TestAdd.test_add_control_dir(view-aware)
        PASS test_add.TestAdd.test_add_dry_run(pre-views)
        PASS test_add.TestAdd.test_add_dry_run(view-aware)

$ testres -s reports/ -t "(teardown)"
Tescase Name: (teardown)
Average Percentage of Fault Detected (APFD): 35%
Average Execution Time: 0.002904
$

.Ed
.Sh STANDARDS
.Rs
.%A M. G. Schwern, A. Lester, A. Armstrong
.%D 2003-2007
.%T TAP 13 - The Test Anything Protocol v13
.Re
.Pp
.Rs
.%A R. Collins
.%D August 2009
.%T SubUnit: A streaming protocol for test results
.Re
.Pp
.Rs
.%A D. Robinson, K. Coar
.%D October 2004
.%R RFC 3875
.%T The Common Gateway Interface (CGI) Version 1.1
.Re
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Sergey Bronnikov
.Sh CAVEATS
Supported formats uses different names and types of test statuses.
For simplification
.Nm
number of statuses limited by PASS, FAIL and SKIP in report summary. These
statuses aggregates other appropriate types of statuses in supported formats.
