/*
 * Copyright © 2018-2019 Sergey Bronnikov
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>
#include <time.h>

#include <sys/types.h>

#include "metrics.h"
#include "parse_common.h"
#include "testres.h"
#include "ui_common.h"
#include "ui_http.h"

extern char **environ;

void print_html_headers() {
    printf("Content-Type: text/html;charset=utf-8\n\n");
    printf("<!DOCTYPE html>\n");
    printf("<html lang='en'>\n");
    printf("<head>\n");
    printf("<title>testres</title>\n");
    printf("<meta name=\"generator\" content=\"testres %s\"/>\n", VERSION);
    printf("<meta name=\"robots\" content=\"index, nofollow\"/>\n");
    printf("<link rel=\"stylesheet\" type=\"text/css\" href=\"%s\" media=\"all\"/>\n", STYLESHEET);
    printf("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/BwAA/zIAAP9jAAD/bgAA/24AAP9XAAD/IQAA/wIAAP8AAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8CAAD/NgAA/6MAAP/mAAD/+wAA//0AAP/9AAD/+AAA/9cAAP+BAAD/HAAA/wAAAP8AAAAAAAAA/wAAAP8BAAD/XAAA/+UAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//gAA/8UAAP8vAAD/AAAA/wAAAP8AAAD/TAAA/+sAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD/xQAA/x8AAP8AAAD/GQAA/8cAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP+LAAD/AQAA/2UAAP/5AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD/2wAA/yYAAP+tAAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//kAAP9dAAD/vgAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP/9AAD/bQAA/74AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//QAA/20AAP+tAAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//kAAP9dAAD/ZQAA//kAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP/bAAD/JgAA/xkAAP/HAAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD/iwAA/wEAAP8AAAD/TAAA/+sAAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD/xQAA/x8AAP8AAAD/AAAA/wEAAP9cAAD/5QAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP/+AAD/xQAA/y8AAP8AAAD/AAAAAAAAAP8AAAD/AgAA/zUAAP+eAAD/5gAA//sAAP/9AAD//QAA//gAAP/WAAD/fAAA/xwAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/BwAA/zIAAP9jAAD/bgAA/24AAP9XAAD/IQAA/wEAAP8AAAAAAAAAAAAAAAAA8A8AAMAHAACAAwAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAEAAIADAADABwAA8A8AAA==\">");
    printf("</head>\n");
    printf("<body>\n");
#ifdef DEBUG
    print_html_env();
#endif /* DEBUG */
}

void print_html_footer() {
    printf("<div><footer class=\"footer\"><small>");
	printf("generated by testres (%s)", VERSION);
    printf("</small></footer></div>\n");
    printf("</body>\n");
    printf("</html>\n");
}

void print_html_search() {
    printf("<div align=\"center\">");
	printf("<form action=\"/%s\" method=\"get\">\n", SCRIPT_NAME);
    printf("  <input type=\"search\" name=\"q\" value=\"\" size=\"60\">\n");
    printf("  <button type=\"submit\">Search</button>\n");
    printf("  <br/>\n");
    printf("</form></div><br>\n");
}

void
print_html_reports(struct reportq * reports) {
    print_html_search();
    printf("<table>\n");
    printf("<tr>\n");
    printf("<th>Report ID</th>\n");
    printf("<th>Success %%</th>\n");
    printf("<th>Status</th>\n");
    /*printf("<th>Created On</th>\n");*/
    printf("</tr>\n");
    tailq_report *report_item = NULL;
	time_t prev_time = {0};
    char datestr[128];
    TAILQ_FOREACH(report_item, reports, entries) {
	    printf("<td><a href=\"/testres.cgi?show=%s\">%s</a></td>\n",
					report_item->id, report_item->id);
	    double perc = calc_success_perc(report_item);
	    if (perc >= 50) {
	       printf("<td><span class=\"label pass\">%0.0f</span></td>\n", perc);
	    } else {
	       printf("<td><span class=\"label fail\">%0.0f</span></td>\n", perc);
	    }
	    printf("<td>\n");
	    printf("<span class=\"label pass\">%d</span>\n",
			num_by_status_class(report_item, STATUS_CLASS_PASS));
	    printf("<span class=\"label fail\">%d</span>\n",
			num_by_status_class(report_item, STATUS_CLASS_FAIL));
	    printf("<span class=\"label skip\">%d</span>\n",
			num_by_status_class(report_item, STATUS_CLASS_SKIP));
	    printf("</td>\n");

        struct tm *date = localtime(&report_item->time);
		double diff = difftime(report_item->time, prev_time);
		if (diff > 60*60*24) {
		   strftime(datestr, 128, "%b %d %H:%M", date);
        } else {
		   strftime(datestr, 128, "%H:%M", date);
		}
        prev_time = report_item->time;
	    printf("<td>%s</td>\n", datestr);
	    printf("</tr>\n");
    }
    printf("</table>\n");
}

void
print_html_report(struct tailq_report * report) {
    print_html_search();
    char buffer[80] = "";
    strftime(buffer, sizeof(buffer), "%b %d %H:%M", localtime(&report->time));
    printf("<table>\n");
    printf("<tr><td><b>Report ID:</b></td><td>%s</td></tr>\n", report->id);
    printf("<tr><td><b>Created On:</b></td><td>%s</td></tr>\n", buffer);
    printf("<tr><td><b>Format:</b></td><td>%s</td></tr>\n", format_string(report->format));
    printf("<tr><td><b>Success Rate:</b></td><td>%0.0f%%</td></tr>\n", calc_success_perc(report));
    printf("<tr><td><b>Slowest Testcase: (> %dsec)</b></td><td>%s</td></tr>\n",
			SLOWEST_THRESHOLD, slowest_testcase(report));
    printf("<tr><td><b>Total Time:</b></td><td>%f</td></tr>\n", report_total_time(report));
    printf("</table>\n");
    printf("<br>\n");	/* FIXME */
    if (!TAILQ_EMPTY(report->suites)) {
       print_html_suites(report->suites);
    }
}

void
print_html_suites(struct suiteq * suites) {
    tailq_suite *suite_item = NULL;
    printf("<table>\n");
    printf("<tr>\n");
    printf("<th>Testcase</th>\n");
    printf("<th>Status</th>\n");
    printf("<th>Time Duration</th>\n");
    printf("<th>Time</th>\n");
    printf("</tr>\n");
    TAILQ_FOREACH(suite_item, suites, entries) {
		if (!TAILQ_EMPTY(suite_item->tests)) {
			print_html_tests(suite_item->tests);
		}
    }
    printf("</table>\n");
}

void
print_html_tests(struct testq * tests) {
    tailq_test *test_item = NULL;
    TAILQ_FOREACH(test_item, tests, entries) {
	printf("<tr>\n");
	const char *name = NULL;
	char buf[16];
	if (test_item->name != NULL) {
		name = test_item->name;
	} else {
		name = "Unknown name";
	}
	printf("<td>%s</td>\n", name);
	printf("<td>%s</td>\n", format_status(test_item->status));
	format_sec(atof(test_item->time), buf);
	printf("<td>%s</td>\n", buf);
	printf("<td></td>\n");
	printf("</tr>\n");
    }
}

void
print_plot(struct reportq *reports) {
    printf("<svg width=\"100%%\" height=\"100%%\">\n");
    printf("<g transform=\"translate(50,50)\"\n>");
    printf("<rect x=\"0\" y=\"0\" width=\"150\" height=\"50\" style=\"fill:red;\" />\n");
    printf("</g>\n");
    printf("</svg>\n");
}

void print_html_env() {
    int i = 1;
    char *s = *environ;
    printf("<pre>\n");
    for (; s; i++) {
        printf("%s\n", s);
        s = *(environ + i);
    }
    printf("</pre>\n");
}
